schema:
  format:
    openapi: "3.0.0"
  service_input_type: "EksBluePrintInput"
  types:
    EksBluePrintInput:
      type: object
      description: "Input properties for my environment"
      properties:
        kubernetes_namespace:
          type: string
          description: "This is k8s namespace"
          default: micro1
        container_version:
          type: string
          description: "This is k8s deployment version"
          default: latest
        resource_cpu_limits:
          type: string
          description: "This is k8s deployment resource cpu limits"
          default: "250m"
        resource_memory_limits:
          type: string
          description: "This is k8s deployment resource memory limits"
          default: "512Mi"
        resource_cpu_requests:
          type: string
          description: "This is k8s deployment resource cpu requests"
          default: "250m"
        resource_memory_requests:
          type: string
          description: "This is k8s deployment resource memory requests"
          default: "50Mi"
        port:
          type: string
          description: "This is k8s service port"
          default: "80"
        target_port:
          type: string
          description: "This is k8s service target port"
          default: "80"
