schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EksBluePrintInput"
  types:
    EksBluePrintInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_name:
          type: string
          description: "This is name for your VPC"
          default: proton-demo
        vpc_cidr:
          type: string
          description: "This CIDR range for your VPC"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        aws_region:
          type: string
          description: "This is your aws region"
          default: us-east-2
        project_environment:
          type: string
          description: "This name for project env"
          default: dev
        project_name:
          type: string
          description: "This name for your project"
          default: demo
        public_subnets_cidrs:
          type: string
          description: "Subnet cidr, enter comma seperates values"
          default: 10.0.101.0/24,10.0.102.0/24,10.0.103.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnets_cidrs:
          type: string
          description: "Subnet cidr, enter comma seperates values"
          default: 10.0.1.0/24,10.0.2.0/24,10.0.3.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        managed_node_groups_instance_types:
          type: string
          description: "EC2 instance type, for multiple types, enter comma seperates values"
          default: "m5.large"
        cluster_version:
          type: string
          description: "The CIDR range for private subnet one"
          default: "1.22"
        managed_node_groups_name:
          type: string
          description: "The CIDR range for private subnet one"
          default: "managed-ondemand"
        cluster_name:
          type: string
          description: "The EKS cluster name"
          default: "proton-eks"
        enable_argocd:
          type: boolean
          description: "The EKS argos addon"
          default: false
        enable_aws_for_fluentbit:
          type: boolean
          description: "The EKS fluentbit addon"
          default: false
        enable_cert_manager:
          type: boolean
          description: "The EKS cert manager addon"
          default: false
        enable_cluster_autoscaler:
          type: boolean
          description: "The EKS cluster autoscaler addon"
          default: false
        enable_karpenter:
          type: boolean
          description: "The EKS karpenter addon"
          default: false
        enable_keda:
          type: boolean
          description: "The EKS keds addon"
          default: false
        enable_metrics_server:
          type: boolean
          description: "The EKS metrics server addon"
          default: false
        enable_prometheus:
          type: boolean
          description: "The EKS prometheus addon"
          default: false
        enable_traefik:
          type: boolean
          description: "The EKS traefik addon"
          default: false
        enable_traefik:
          type: boolean
          description: "The EKS traefik addon"
          default: false
        enable_vpa:
          type: boolean
          description: "The EKS vpc addon"
          default: false
        enable_yunikorn:
          type: boolean
          description: "The EKS yunikorn addon"
          default: false
        enable_argo_rollouts:
          type: boolean
          description: "The EKS argo_rollouts addon"
          default: false